### PR TITLE
added path seperator as a cli var for cases where path.sep is undefined

### PR DESCRIPTION
**Pull request by yamanote1138**
Added 'pathsep' as a CLI var (or .groc.json config var), figured it might be worth sharing.   If the pathsep var is not provided and path.sep is undefined, path.sep is set to '/'.

I'm not terribly familiar with coffeescript, so please double-check me if you can :)

I had to make this change as we're running node v0.6.20, so path.sep was undefined.  I couldn't get groc to generate relative paths no matter what i tried config-wise.  A little bit of console logging exposed a whole bunch of 'undefined' getting injected into stripPaths because of the reliance on path.sep (which isn't introduced until node v0.8, I think).

### CODE REVIEW

**Comment by Prestaul** [comment]
+1  Yes, please.  We're stuck on a corporate installation of v0.6 for now.  Until we can get up to v0.8 we can't use groc without this fix.

**Comment by nevir** [comment]
Hmm, I'm not a fan of making this configurable; going to see about just detecting windows on 0.6 and below

**Comment by yamanote1138** [comment]
works for me :)

**Comment by yamanote1138** [comment]
for what it's worth, we ended up just adding `path.sep='/';` to the wrapper script we use to kick off groc
just figured i'd put this out there to save anyone that's stuck on a early version of node like we are :P

**Comment by nevir** [comment]
Alright, groc 0.2.17 is in and it's got some simplistic path.sep detection; shouldn't need your hacks any more :)

**Pull request closed without merging**
