### PR TITLE
Add a "github-url" configuration option

### PR DESCRIPTION
**Pull request by msteinert**
This is particularly useful for Github:enterprise installations.

### CODE REVIEW

**Comment by yamanote1138** [comment]
nice work!! we're in the same boat, so definitely a +1 on my part :)

**Comment by nevir** [comment]
Hey, sorry about the delay on this one; work is predictably eating me alive :(  Testing this out now

**Comment by yamanote1138** [comment]
no worries, I know the feeling :)

**Comment by nevir** [comment]
Alright, this is in groc v0.2.17 - **note** that I renamed the option to `repository-url` to (hopefully) avoid some confusion around which part of the URL to use

**Pull request closed without merging**
