### PR TITLE
Switch to Highlight.js

### PR DESCRIPTION
**Pull request by killercup**
As discussed in #134.

I chose to switch to [highlight.js](http://highlightjs.org/) because I dislike the python dependency and how slow the invocation of child processes is. To render groc's own documentation, groc with pygments takes 9.5s on my machine, whereas groc with highlight only needs 3s (medium of 5 tests).

This pull request also includes my crude attempt at converting the original stylesheet to a highlight-compatible format (in SCSS) and adds the `highlightJS` key to some language definitions where the name highlight uses differs from pygment's.

<del>In general, I'm only changing the `highlightCode` method in `utils.coffee`. If you want to keep pygments available, I suggest you change `highlightCode` to call specific methods depending on an option, e.g. `highlightCodeHighlightJS` and `highlightCodePygments`.</del>

<ins>I've replaced `highlightCode` with `highlightCodeUsingHighlighJS` and `highlightCodeUsingPygments`. You can set your highlighter preference using the 'highlighter' CLI option or `.groc.json` property.</ins>

Stay tuned for my next PR to switch to marked.js.

### CODE REVIEW

**Comment by sjorek** [comment]
Just to mention: the figures from “pygments takes 9.5s ” are the result of forking one process per source-file in groc. :smirk:

**Comment by killercup** [comment]
@sjorek of course, thats why I wanted a solution that didn't have to fork anything at all. :)

I hope @kmdavis likes this PR!

**Comment by killercup** [comment]
Voilá, `groc --highlighter=pygments` is all yours.

I would like to refactor the highlighting stylesheets next, but it's not really important and also a whole other issue. Ideally, I'd like to try to create one for all highlighters, just by using SASS variables. (It would also be nice if there was more than one design and if one could compile the SASS sources using libsass.)

**Comment by kmdavis** [comment]
love the cli option.  also like not depending on python :smile:

**Comment by killercup** [comment]
Any news when this will be merged? I'd really like to tell npm to use `groc`, not `git://github.com/killercup/groc#da6ff644c1596ff97ee3315f9461cc3c6ea43444` ;)

**Comment by ctumolosus** [comment]
+1

**Comment by killercup** [comment]
For all those who are waiting on this PR:

Over the last week or so I've been writing an **alternative implementation of groc**. The main differences are that it
- uses streams to process a glob of files (which makes is quite easy to read)
- uses marked and highlight.js (which makes it quite fast)
- uses a different style based on Solarized with a responsive layout and a sidebar with file tree and headline toc (that I initially wrote for groc though)

It's quite stable right now but probably hasn't been tested enough. You can find the project at https://github.com/killercup/grock.

I want to thank the groc authors very much -- some of the "hard parts" (splitting code and comments, list doc tags and languages) are borrowed code groc. Without those it wouldn't have been possible to implement any of this functionality this quickly.

**Comment by longlho** [comment]
+1 for this

**Comment by despairblue** [comment]
:+1:

**Comment by jessefulton** [comment]
+1

**Comment by nevir** [comment]
Months late, but thanks for this - merged :)

**Pull request closed without merging**
