### PR TITLE
Fixed doctype

### PR DESCRIPTION
**Pull request by imor**
Latest jade expects 'doctype html' instead of '!!! 5'

### CODE REVIEW

**Comment by mansona** [comment]
this would be very good to get merged... if at all possible :)

**Comment by joshuatoenyes** [comment]
Thanks @imor. I manually applied your patch. Works like a champ.

**Comment by ctumolosus** [comment]
+1

**Comment by brianbouril** [comment]
Manually applying the fix works but it would be great to get this merged please :)

**Comment by dominicbosch** [comment]
+1, merge please!

**Comment by jewelsjacobs** [comment]
:+1:

**Comment by kmdavis** [comment]
merged #155 instead

**Pull request closed without merging**
