### PR TITLE
Short-term fix for jade@1.0.0 breaking changes

### PR DESCRIPTION
**Pull request by scottnonnenberg**
jade 1.0.0 breaks groc:

```
Warning: Jade:1
  > 1| !!! 5
    2| html(lang="en")
    3|   head
    4|     title= pageTitle
`!!!` is deprecated, you must now use `doctype`
```

Unfortunately, because the dependency is specified as "jade": ">= 0.17.0" in the package.json, any new or updated installations are broken right now. This small change will fix them until groc is compatible with jade@1.0.0.

### CODE REVIEW

**Comment by hszcg** [comment]
Hi, I am wondering that when could you push these changes into npm, current npm package it is broken with jade 1.x.

Thanks a lot.

**Comment by jewelsjacobs** [comment]
:+1:

**Comment by jdcataldo** [comment]
@nevir @kmdavis Any chance of getting this published to npm?

**Comment by variousauthors** [comment]
How does this fix work? I changed the jade version in the package.json file but am still getting the warning. Is there some equivalent to `bundle update` I need to do?

**Comment by kmdavis** [comment]
You should only have to do an `npm install`

**Comment by variousauthors** [comment]
Ah ha! Everything is perfect now, love you guys!

**Pull request merged**
