### PR TITLE
Adds support for folding blocks of code

### PR DESCRIPTION
**Pull request by achingbrain**
Some code like imports/require blocks, internal methods/helpers etc can clutter the generated docs making it harder to see what's going on.

Inspired by [Atlassian's version of docco](https://bitbucket.org/doklovic_atlassian/atlassian-docco/wiki/writing-docco-comments) I've added the ability to do this sort of thing:

``` javascript
//- Imports
var foo = require("something");

// Some interesting code
var bar = new foo();
```

The generated documentation will contain a marker for the code following the //- Imports comment and all code until the next comment - the code is hidden by default but will be shown if you click on the marker.

It also doesn't show the - or } characters at the beginning of single line comments in the generated docs where they are present.

I'm happy to discuss these changes.

### CODE REVIEW

**Comment by sjorek** [comment]
This breaks **_“@param”**_-doctags - they still appear, but split into individual sections, like:

```
Parameters:
    action must be a Processor.
        (The calling action)

Parameters:
    context must be a Context.
        (The current evaluation context)

Parameters:
    template must be a Node.
        (The currently processed node of the template)

Parameters:
    attribute must be a Function.
        (Processed value of the content attribute)

Returns a Boolean
```

Correct would be:

```
Parameters:
    action must be a Processor.
        (The calling action)

    context must be a Context.
        (The current evaluation context)

    template must be a Node.
        (The currently processed node of the template)

    attribute must be a Function.
        (Processed value of the content attribute)

Returns a Boolean
```

I didn't look deeper in to the code - just wanted to mention this.

**Comment by achingbrain** [comment]
Good spot - I've updated the pull request to not do that..

**Comment by kmdavis** [comment]
This commit mostly looks good... except that it's too eager. If you run groc on itself, you'll find that on most pages, the first code block is folded, but it shouldn't be. I'm currently debugging, and I'll update this when I figure it out.

**Comment by kmdavis** [comment]
update: it happens after any comment which is just a header

**Comment by kmdavis** [comment]
ok, finally found a chance to look at this again.  Turns out the 'foldMarker' was null or undefined... which, in jade, isn't equal to '' (via !=)

I'll merge, then commit a quick fix

**Comment by achingbrain** [comment]
Oops, rookie error.  Sorry, this is the first time I've tried to do anything with Jade.

**Comment by sjorek** [comment]
@achingbrain did you notice the new pull-request above … ?

**Pull request merged**
